version: '3'

services: 
    consulserver01:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver01
        hostname: consulserver01
        command: ['tail', '-f', '/dev/null']
        volumes: 
            - ./servers/server01:/etc/consul.d
        ports:
            - "8500:8500"
        networks:
            network:
                ipv4_address: 10.5.0.2

    consulserver02:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver02
        hostname: consulserver02
        command: ['tail', '-f', '/dev/null']
        volumes: 
            - ./servers/server02:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.3

    consulserver03:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver03
        hostname: consulserver03
        command: ['tail', '-f', '/dev/null']
        volumes: 
            - ./servers/server03:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.4

    consulclient01:   
        build:
            context: .
            dockerfile: DockerfileClient
        container_name: consulclient01
        hostname: consulclient01
        command: sh -c "nginx && tail -f /dev/null"
        volumes: 
            - ./clients/client01:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.5

    consulclient02:   
        build:
            context: .
            dockerfile: DockerfileClient
        container_name: consulclient02
        hostname: consulclient02
        command: sh -c "nginx && tail -f /dev/null"
        volumes: 
            - ./clients/client02:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.6

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16