version: '3'

services: 
    consulserver01:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver01
        hostname: consulserver01
        command: ['tail', '-f', '/dev/null']
        networks:
            network:
                ipv4_address: 10.5.0.2

    consulserver02:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver02
        hostname: consulserver02
        command: ['tail', '-f', '/dev/null']
        networks:
            network:
                ipv4_address: 10.5.0.3

    consulserver03:   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consulserver03
        hostname: consulserver03
        command: ['tail', '-f', '/dev/null']
        networks:
            network:
                ipv4_address: 10.5.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16